import streamlit as st
import numpy as np
import pandas as pd

st.set_page_config(page_title = 'LGBT and Refugee Rights in Europe - Conclusion', layout = 'wide', page_icon = 'ikona_uniwersytetu.png')
im1, im2, im3, im4, im5 = st.columns([1,1,1.5,1.5,1.5])
with im1:
    st.image('logo_fundacji.png')
with im2:
    st.image('logo_uniwersytetu.png')
st.title(':violet[References]')

st.markdown('<div style="text-align: justify;">1. The Bulgarian Council on Refugees and Migrants. <href>https://bcrm-bg.org/en/</href>.<br /> 2. Drouhot, L.G., Schönwälder, K., Petermann, S. et al. “Who supports refugees? Diversity assent and pro-refugee engagement in Germany.” CMS, vol. 11, 2023, <href>https://doi.org/10.1186/s40878-023-00327-2</href>.<br />3. “European Union: Bloc backs plan for stricter asylum reforms – DW – 06/08/2023.” DW, 2023, <href>https://www.dw.com/en/european-union-bloc-backs-plan-for-stricter-asylum-reforms/a-65861983</href>.<br />4. “Kantar survey for UNHCR: Majority of Poles now in favour of accepting refugees.” National Integration Evaluation Mechanism, 2021, <href>http://www.forintegration.eu/pl/kantar-survey-for-unhcr-majority-of-poles-now-in-favour-of-accepting-refugees</href>.<br /> 5.Open ended social studies. Refugees and Human Rights in Bulgaria. 2017, <href>https://openendedsocialstudies.org/2017/11/14/refugees-and-human-rights-in-bulgaria/</href>.<br />6. Rainbow Europe. “Bulgaria.” 2021, <href>https://rainbow-europe.org/country-ranking?order=field_country_rank&sort=asc</href>.<br />7. Rainbow Europe. “Germany.” 2021, <href>https://rainbow-europe.org/country-ranking?order=field_country_rank&sort=asc</href>.<br />8. Rainbow Europe. “Poland.” 2021, <href>https://rainbow-europe.org/country-ranking?order=field_country_rank&sort=asc</href>.<br />9. RFE/RL. The Worrying Regression Of LGBT Rights In Eastern Europe. 2021, <href>https://www.rferl.org/a/lgbt-rights-eastern-europe-backsliding/31622890.html</href>.<br />10. Rice, Mark. “Poland has worked a refugee miracle. But how much longer can it last?” The Guardian, 2022, <href>https://www.theguardian.com/global-development/2022/apr/06/poland-has-worked-a-refugee-miracle-but-how-much-longer-can-it-last</href>.<br />11. UNHCR. “Germany.” 2021, <href>https://www.unhcr.org/germany.html</href>.<br />12. UNHCR Bulgaria. “Help for refugees and asylum-seekers.” 2019.<br /> 13. UNICEF. “Joining forces to meet unprecedented need: How Bulgaria has responded to the Ukrainian refugee crisis.” 2022, <href>https://www.who.int/europe/news/item/20-10-2022-joining-forces-to-meet-unprecedented-need–how-bulgaria-has-responded-to-the-ukrainian-refugee-crisis</href>.<br />14. “UNICEF Refugee Response Office in Poland.” UNICEF, <href>https://www.unicef.org/eca/poland</href>.</div>', unsafe_allow_html=True)